import { useState } from 'react';
import { MainGrid } from './components/MainGrid';
import { Search } from './components/Search';

import { getLongitudeAndLatitudes, selectLocation as selectLocationRedux } from './actions/location/actions'
import { useDispatch, useSelector } from 'react-redux';
import { RootStore } from './store/store';
import { LocationsState } from './reducers/locationsReducer';
import { getDailyWeatherForecasts } from './actions/weather/actions';
import { WeatherForecastState } from './reducers/weatherForecastReducer';
import { useEffect } from 'react';
import { Location } from './model/location';
import { Forecasts } from './components/ForecastsGrid';
import { Error } from './components/Error';
import { Header } from './components/Header';

function App() {
      const dispatch = useDispatch()

      // Hold the entered query in the state

      const [query, setQuery] = useState('')

      // The following lines retrieve all the significant properties generated by the redux activity
      const { locations, loading: loadingLocations, selectedLocation}: LocationsState  = useSelector((state: RootStore) => state.locations)
      const { weather, loading: loadingForecast}: WeatherForecastState  = useSelector((state: RootStore) => state.weatherForecast)
      const error : string  = useSelector((state: RootStore) => state.error)

      // Get the Latitude and Longitude of the selected location
      const { lat, lon} = selectedLocation || {}

      // The use effect will respond to any selecion of a location and trigger and call to get the 7 day forecasts
      useEffect(() => {
        if ((!!lat) && (!!lon)) {
          dispatch(getDailyWeatherForecasts(lat, lon))
        }
      }, [lat, lon, dispatch])

      // Check if anything is still loading

      const loading = loadingLocations || loadingForecast

      // add the redux dispatch of the API calls which are supplied to the sub-components - see below

      const search = (query: string) => {
        dispatch(getLongitudeAndLatitudes(query))
      }
      const selectLocation = (location: Location) => {
        dispatch(selectLocationRedux(location))
      }
      
      return (
          <MainGrid loading={loading}>
            <Header heading={"7 Day Weather Forecasts By Location (Lat/Lon)"}/> 
            <Search 
                  query={query} 
                  setQuery={setQuery} 
                  search={search} 
                  selectedLocation={selectedLocation} 
                  loading={loading}
                  locations={locations}
                  selectLocation={selectLocation}/>
            <Error message={error}/>
            <Forecasts weather={weather} selectedLocation={selectedLocation}></Forecasts>
          </MainGrid>
        );
}

export default App;
